### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by camallen** [zooniverse/alice#210]
Currently any changes require manual deployments to be run by the developer via these scripts, https://github.com/zooniverse/text-editor/blob/0316f4753724a1cd48357e7a95c8bc680778667e/package.json#L52-L53

This codebase requires the ability to autodeploy the changes to our static app targets (azure blob store / s3). We need to add CI and CD via similar work to https://github.com/zooniverse/anti-slavery-manuscripts/pull/323

**Comment by srallen** [comment]
This is done.
