### ISSUE TITLE
User status doesn't reflect my actual status and permissions

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/alice#330]
When I'm logged in, my account has admin privileges, but the account status on the top right says 'Viewer', not 'Admin'.
![Screenshot of my avatar and name, with my role shown as 'viewer'](https://user-images.githubusercontent.com/59547/169582721-73981438-5f37-4d6e-8827-5fdbdc1c3809.png)

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/alice/blob/2f287eda190b96827806076e38acefc27b4fc706/src/store/TranscriptionsStore.spec.js#L366-L369

This test doesn't add a current transcription to the mocked store. So it's really testing that the locked document warning can appear while the store is empty. I don't know if that's directly related to this issue but the test passes, which points to a bug in `store.transcriptions.current`. Perhaps `checkIfLocked` runs while the page is loading?

Found while working on #333.

**Comment by snblickhan** [comment]
I'm not sure if the 'status doesn't reflect actual status/permissions' diagnosis is the only thing happening here. Mine seems to actually reflect the wrong permissions. I'm listed as a Collaborator on project `4973` (Anti-Slavery Manuscripts) and am listed in ALICE as a Viewer (see screenshot below):
 
<img width="1153" alt="Screenshot 2023-07-20 at 10 19 06 PM" src="https://github.com/zooniverse/alice/assets/25958358/502460b6-91da-404d-8c29-9fd46e1d08fd">

If I had actual Admin privileges and was just incorrectly listed, I'd expect to see a lot of buttons at the top of the page, including the option to Unapprove the subject, as well as the 'More' dropdown, which lets you download Approved subject data. Here's what an Approved subject looks like on a project where I'm an Admin: 

<img width="1144" alt="Screenshot 2023-07-20 at 10 23 18 PM" src="https://github.com/zooniverse/alice/assets/25958358/edcdadfe-034c-495a-86ae-7b1f615fc100">

Might be something else going on?

**Comment by eatyourgreens** [comment]
That’s interesting. I didn’t see those buttons either, but API requests were made with admin privileges.

**Comment by eatyourgreens** [comment]
I’m trying to remember what I meant when I wrote up this issue. It was a long time ago, but I think I meant that I could see projects even when I’m not on the team. 

Something weird is going on with roles, though. 

According to the git history, 'admin' used to be called 'researcher'. I’m a collaborator on a project, which should give me the ‘researcher’ role, but still show up as a Viewer, not Admin, for that project in Alice.

**Comment by eatyourgreens** [comment]
Here's a screenshot from browser dev tools, for a project where I'm a collaborator. The API request for project roles is coming back empty from Panoptes. It was sent with the correct Authorization header, and this is for a single project, so pagination isn't a problem. 

![Screenshot of the API response for project roles. Roles are empty, even though I'm a collaborator.](https://github.com/zooniverse/alice/assets/59547/39962a4c-02c8-4167-9903-e1c5d1373aa1)

**Comment by eatyourgreens** [comment]
Nevermind. If I make sure that Collaborator and/or Researcher are checked in the project builder, then project roles work for my account. 

![Screenshot of an Alice page on my phone, showing my account logged in as an admin, with additional admin controls available.](https://github.com/zooniverse/alice/assets/59547/5cef253c-502c-4059-a5ff-991a9e2b6012)
